// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2AaCF6IzlWcsm9hOYtyhPdPB-snutGu0',
    appId: '1:566472544855:web:046d2abdee7f2560870912',
    messagingSenderId: '566472544855',
    projectId: 'instagramclone-7bbe8',
    authDomain: 'instagramclone-7bbe8.firebaseapp.com',
    storageBucket: 'instagramclone-7bbe8.firebasestorage.app',
    measurementId: 'G-QY37W2F8E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFyFtGZv8kDlbyvRZZGtVB-njE3mqcJX8',
    appId: '1:566472544855:android:abf380a9af7a91b6870912',
    messagingSenderId: '566472544855',
    projectId: 'instagramclone-7bbe8',
    storageBucket: 'instagramclone-7bbe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBXI-onREuuGxvIXGzYcL9z1yYjALCxkU',
    appId: '1:566472544855:ios:3f21288fc96bbbb9870912',
    messagingSenderId: '566472544855',
    projectId: 'instagramclone-7bbe8',
    storageBucket: 'instagramclone-7bbe8.firebasestorage.app',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBXI-onREuuGxvIXGzYcL9z1yYjALCxkU',
    appId: '1:566472544855:ios:3f21288fc96bbbb9870912',
    messagingSenderId: '566472544855',
    projectId: 'instagramclone-7bbe8',
    storageBucket: 'instagramclone-7bbe8.firebasestorage.app',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2AaCF6IzlWcsm9hOYtyhPdPB-snutGu0',
    appId: '1:566472544855:web:518d5ee55e710b29870912',
    messagingSenderId: '566472544855',
    projectId: 'instagramclone-7bbe8',
    authDomain: 'instagramclone-7bbe8.firebaseapp.com',
    storageBucket: 'instagramclone-7bbe8.firebasestorage.app',
    measurementId: 'G-0Q0XJP4829',
  );

}